version: "3.7"
services:
  backend_base: &backendbase
    build:
      context: ./backend
      args:
        EXTRA_PACKAGES: graphviz graphviz-dev
        ENVIRONMENT: ${ENVIRONMENT}

  worker:
    <<: *backendbase

  backend:
    <<: *backendbase
    expose:
      - "8000"
    ports:
      - "8000:8000"
